soda-inria/sklearn-numba-dpex

docker/Dockerfile

This Dockerfile should enable a working environment with a set of nice properties:
- a standard environment
- easy installation
- reproducibility
- configurability (set python, dpctl, dpnp, numba-dpex, intel numpy, intel scipy, intel numba versions)
and it gives an overview of the packaging of intel softwares used for numba-dpex and their contents.

Add a Dockerfile for building a numba_dpex dev environment

---

docker/Dockerfile
sklearn_numba_dpex/tests/test_kmeans.py

The 0.18.1 version from "numba_dpex" switches from `numba_dppy` module name to `numba_dpex`, from then on imports must refer to the latter.

updating Dockerfile to latest dpctl, dpnp and numba_dpex releases

---

.github/workflows/run_code_format_checks.yaml
.github/workflows/run_tests.yaml
.pre-commit-config.yaml
pyproject.toml
setup.py
sklearn_numba_dpex/kmeans/kernels.py
sklearn_numba_dpex/tests/test_kmeans.py
sklearn_numba_dpex/utils/_device.py
sklearn_numba_dpex/utils/tests/test_device_params.py

This:
- tune black correctly
- use `isort` to sort import canonically
- add a GitHub workflow to run format checks
Potentially we could have a single workflow with two jobs (one for those checks and another for the CI). What do you think?

CI Improve pre-commit setup and run it on the CI

---

sklearn_numba_dpex/kmeans/drivers.py
sklearn_numba_dpex/kmeans/kernels.py

We have currently [this kernel](https://github.com/soda-inria/sklearn-numba-dpex/blob/main/sklearn_numba_dpex/kmeans/kernels.py#L75) and [this kernel](https://github.com/soda-inria/sklearn-numba-dpex/blob/main/sklearn_numba_dpex/kmeans/kernels.py#L344) that have duplicated code, meaning if changes happen on one kernel probably it should be propagated to the other one, which is not very good for maintaining.
But `numba_dpex` kernels can only be refactored using `numba_dpex.func`-decored [device functions](https://intelpython.github.io/numba-dpex/latest/user_guides/kernel_programming_guide/device-functions.html) and those have a limited set of features, e.g. you can't use barriers inside or create arrays, those particular steps must be in the body of the kernel. In this case those parts are …

Reduce the number of duplicated codes in kmeans kernel

---

sklearn_numba_dpex/kmeans/drivers.py
sklearn_numba_dpex/kmeans/kernels/__init__.py
sklearn_numba_dpex/kmeans/kernels/utils.py
sklearn_numba_dpex/tests/test_kmeans.py

This is a first step toward appropriate dealing of empty clusters.
In this PR we detect empty clusters when it happens during the lloyd algorithm and issue a warning when it happens.
Future work will implement the exact behavior that we have in scikit learn. In the short term I want to prioritize the plugin interface and probably will come to empty clusters only afterward (or maybe somebody else want to give it a try before me)
But since I had this part pending I think we could merge it already.

Detect empty clusters during lloyd algorithm and issue a warning

---

sklearn_numba_dpex/kmeans/drivers.py
sklearn_numba_dpex/kmeans/kernels/utils.py
sklearn_numba_dpex/tests/test_kmeans.py

First of a few cleaning PR for preparation of the review of https://github.com/soda-inria/sklearn-numba-dpex/pull/37
This PR is only about replacing `dpct.tensor` with `dpt`.
Using `dpt` in place of `dpt.tensor` seems to be common e.g https://github.com/IntelPython/numba-dpex/search?q=%22import+dpctl.tensor%22 or https://github.com/IntelPython/dpnp/search?q=%22import+dpctl.tensor%22 .

Replace dpctl.tensor with dpt

---

benchmark/ext_helpers/daal4py.py
benchmark/kmeans.py

The purpose of this PR is to make it easier to write additional methods to the daal4py engine used in benchmarks, in particular the `prepare_fit` i also defined to raise errors for unsupported parameters.
To merge before https://github.com/soda-inria/sklearn-numba-dpex/pull/37 and after https://github.com/soda-inria/sklearn-numba-dpex/pull/39

Use engine-style implementation for daal4py benchmark

---

sklearn_numba_dpex/kmeans/drivers.py
sklearn_numba_dpex/kmeans/kernels/compute_inertia.py
sklearn_numba_dpex/kmeans/kernels/lloyd_single_step.py
sklearn_numba_dpex/kmeans/kernels/utils.py

The goal now that our KMeans is complete is to work toward enabling the use of the estimators with the `sklearn_numba_dpex` engine with inputs that are not numpy arrays but dpnp arrays or dpt tensors, with a satisfying level of input validation, and while keeping the level of features that we currently have (in particular testing against sklearn unit tests).
It is harder than it sounds and I've been running in circle trying to achieve this, I'll work toward a sequence of small PRs to make data conversions easier to track, by:
- decoupling data validation/conversion steps and actual compute
- leveraging "compute follow data" model to minimize the number of occurences of data parameters in the pipeline
This PR is a small refactoring of the KMeans driver where the data conversion steps are …

Refacto: get data conversion steps more visible

---

sklearn_numba_dpex/common/_utils.py
sklearn_numba_dpex/common/kernels.py
sklearn_numba_dpex/common/tests/test_kernels.py
sklearn_numba_dpex/kmeans/drivers.py

Two things in this PR:
Not sure what is better, using those kernels or using `dpnp` functions.
Pros for using those kernels:
- limit the dependency to `dpnp` (which can especially be a good things if `numba_dpex` get interoperability to nvidia/amd gpus before `dpnp` does)
- more confidence regarding the strategy for dispatching to thread that fit more GPU devices, it's not clear at what point `dpnp` can run well on gpus
- fun
Cons for using those kernels:
- it's verbose, and if we want to optimize other usecases (depending if axis0 is "big enough", or else which is bigger from axis 0 or axis 1,...) it would require yet other kernels.
- it does not sound like it's a good thing to jit those simple operations, the added jit time might get annoying
- at some point, it can be assumed that a …

Extend sum reduction kernel, add argmin reduction kernel

---

sklearn_numba_dpex/common/random.py
sklearn_numba_dpex/common/tests/test_random.py

Same PR than https://github.com/soda-inria/sklearn-numba-dpex/pull/42 that I closed by mistake
This time, with tests
The tests take randomgen implementation as reference, but I've found errors in randomgen while writing the tests, until the errors are confirmed (reported in https://github.com/bashtage/randomgen/issues/321 ) our implementation is corrupted with the same errors for the moment. 
Maybe another reference implementation would be preferable if you have suggestions. I prefer not to use `numba.cuda.random` as reference because it requires a GPU to check it.

Rng kernels

---

sklearn_numba_dpex/kmeans/drivers.py

I forgot about it and was confused by the existing message of the `ValueError` raised in `sklearn_numba_dpex` (https://github.com/IntelPython/numba-dpex/issues/767).

Reference the numba_dpex f-layout bug

---

docker/Dockerfile
sklearn_numba_dpex/device/device.py
sklearn_numba_dpex/device/tests/test_device_params.py
sklearn_numba_dpex/kmeans/drivers.py

First step towards solving https://github.com/soda-inria/sklearn-numba-dpex/issues/52
The use of `dpctl==0.14.0rc2` unlocks early the use of `dpctl.SyclDevice.sub_group_sizes` if you want to check the values on your machines.
I check that all tests passes before pushing and the benchmark is unchanged.

ENH Up to date dockerfile

---

sklearn_numba_dpex/kmeans/kernels/_base_kmeans_kernel_funcs.py
sklearn_numba_dpex/kmeans/kernels/compute_euclidean_distances.py
sklearn_numba_dpex/kmeans/kernels/compute_labels.py
sklearn_numba_dpex/kmeans/kernels/kmeans_plusplus.py
sklearn_numba_dpex/kmeans/kernels/lloyd_single_step.py

On main branch currently, if the size of the window over centroids does not divide the size of the array of centroids, windows on the edge are filled with zeros, but compute still takes place for those zeros, In unlucky setups (e.g small number of dimensions and/or clusters, and increased size of window) most of the time can be spent there. The fix consists in exiting the loops over elements of the window so that no compute is performed over the extra zero padding.

ENH Fix kernels that wasted overhead compute on out-of-bounds memory

---

benchmark/kmeans.py

The inter-run variability is typically much larger than 100 ms so there is not point reporting too many falsely significant digits.

Benchmark: do not report timings under 100ms precision level

---

benchmark/ext_helpers/daal4py.py
benchmark/kmeans.py
sklearn_numba_dpex/common/_utils.py
sklearn_numba_dpex/common/kernels.py
sklearn_numba_dpex/kmeans/drivers.py
sklearn_numba_dpex/kmeans/engine.py
sklearn_numba_dpex/kmeans/tests/test_kmeans.py
sklearn_numba_dpex/testing/config.py

I think I'm happy with the result, the code is a little messy but not more than sklearn's and I think the PR basically succeeds in mimicking almost all aspects of sklearn's UX regarding what inputs are accepted and how it's casted under the hood, and also performance regarding the cautiousness with memory copies, while additionally creating support for `dpnp.ndarray` and `dpt.usm_ndarray` inputs, and recycling the most possible code that already exists in sklearn.
The PR still needs some polishing, and a few tests with `dpnp`/`dpt` tensors.
I think one (minor) difference is that, while sklearn try to convert numpy arrays with `object` dtype to `float64`, our engine will error out in this case because `dpt.asarray` refuses object dtype as input. Those kind of edge cases are complicated to …

FEA: engine accepts dpnp.ndarray and dpt.usm_ndarray objects as input data.

---

.github/workflows/run_tests.yaml
sklearn_numba_dpex/kmeans/drivers.py
sklearn_numba_dpex/kmeans/engine.py
sklearn_numba_dpex/kmeans/kernels/__init__.py
sklearn_numba_dpex/kmeans/kernels/utils.py
sklearn_numba_dpex/kmeans/tests/test_kmeans.py

~~The compatibility layer for having the sklearn test keep working is still TODO.~~ Let alone that, I think this would be the final state of `KMeansEngine`.

ENH: Store fitted attributes as dpt and return dpt tensors

---

sklearn_numba_dpex/common/_utils.py
sklearn_numba_dpex/common/kernels.py
sklearn_numba_dpex/kmeans/drivers.py
sklearn_numba_dpex/kmeans/engine.py
sklearn_numba_dpex/kmeans/tests/test_kmeans.py

This PR is a prerequisite for https://github.com/soda-inria/sklearn-numba-dpex/pull/68
Before  `dpnp==0.11.0` (NB: our current image uses `0.11.0rc1`) some calls to `dpnp` could silently fallback on `numpy`. [From `0.11.0` on](https://github.com/IntelPython/dpnp/pull/1201) the silent fallback is removed and an error is raised instead (the fallback mode can be reactivated with an environment variable `DPNP_RAISE_EXCEPION_ON_NUMPY_FALLBACK`).
That breaks our code at several locations:
- direct call to `take` triggers a fallback
- broadcasting binary operations [triggers fallbacks](https://github.com/IntelPython/dpnp/issues/1238) (!!) 
I'm worried that silent fallbacks on numpy when running on gpu could have dramatic effects on performance if it could trigger memory transfers. Rather than …

FIX: Prepare for dpnp 0.11.0

---

README.md

To be reverted when https://github.com/IntelPython/dpctl/issues/1022 is closed

Temporarily pin dpcpp runtime in conda install

---

docker/Dockerfile

This fix the runtime issues from the build from last night, caused by a version mismatch between the build dependency in the oneapi basekit (libsycl 0.5, 2022.x.x) and the the runtime dependencies python packages that were recently updated to pypi (from 2022.x.x to 2023.x.x, bumping libsycl to 0.6).

Update dockerfile to up to date versions

---

benchmark/ext_helpers/kmeans_dpcpp.py
benchmark/kmeans.py

Benchmark results:
```
Running Sklearn vanilla lloyd with parameters sample_weight=unary n_clusters=127 data_shape=(263256, 14) max_iter=100...
Running Sklearn vanilla lloyd ... done in 1.3 s
Running kmeans_dpcpp lloyd GPU with parameters sample_weight=unary n_clusters=127 data_shape=(263256, 14) max_iter=100...
/sklearn-numba-dpex/benchmark/./kmeans.py:108: ConvergenceWarning: Number of distinct clusters (32) found smaller than n_clusters (127). Possibly due to duplicate points in X.
KMeans(**est_kwargs).set_params(max_iter=1).fit(
/sklearn-numba-dpex/benchmark/./kmeans.py:116: ConvergenceWarning: Number of distinct clusters (28) found smaller than n_clusters (127). Possibly due to duplicate points in X.
estimator.fit(X, sample_weight=sample_weight)
Running kmeans_dpcpp lloyd GPU ... …
```

Add kmeans_dpcpp to benchmark

---

benchmark/ext_helpers/kmeans_dpcpp.py
benchmark/kmeans.py
sklearn_numba_dpex/common/kernels.py
sklearn_numba_dpex/common/random.py
sklearn_numba_dpex/kmeans/drivers.py

Revert some changes in one of the last cleaning commits in  https://github.com/soda-inria/sklearn-numba-dpex/pull/82 Those changes disrupted the caching of some kernels, causing re-compiling at each iteration in kmeans, with a big performance hit.
Also improves the performance of kmeans++ since there were an even older issue with caching in the random module. 
This issue also teach us that bugs in caching can be disastrous and are totally silent and should always require special care.

Fix a bug that caused some kmeans helper kernels to not be correctly cached

---

README.md
sklearn_numba_dpex/common/_utils.py
sklearn_numba_dpex/kmeans/drivers.py
sklearn_numba_dpex/kmeans/kernels/compute_labels.py
sklearn_numba_dpex/kmeans/kernels/kmeans_plusplus.py
sklearn_numba_dpex/kmeans/kernels/lloyd_single_step.py

- pin numba_dpex build from dppy/label/dev conda channel
- use a default hardcoded value when device global memory cache size can't be fetched
For the latter fix it will be interesting to test during the next session on the devcloud if clinfo also fails at finding `global_memory_cache_size`, else we could use `pyopencl`.

Fix issues seen on devcloud with flex170 gpu

---

sklearn_numba_dpex/kmeans/tests/test_kmeans.py

My `max_work_group_size` is 256.
```python
>>> import dpctl
>>> dpctl.SyclDevice()
<dpctl.SyclDevice [backend_type.opencl, device_type.gpu,  Intel(R) Iris(R) Graphics 540 [0x1926]] at 0x7ff4e77fc5f0>
```

FIX make test_error_raised_on_invalid_group_sizes pass on smaller GPUs

---

sklearn_numba_dpex/common/kernels.py

Here is my attempt to make the sum reduction kernel related code more intuitive to a newcomer. It's a mix of change of variable name, order of code blocks and improvements to the docstrings / comments.
I still have follow-up work to do but I am not sure when I will have the time to continue this work, so feel free to edit / improve / merge as you wish without waiting for me.

Improve understandability of the sum reduction kernels

---

sklearn_numba_dpex/common/__init__.py
sklearn_numba_dpex/common/reductions.py
sklearn_numba_dpex/kmeans/kernels/_base_kmeans_kernel_funcs.py
sklearn_numba_dpex/kmeans/kernels/compute_euclidean_distances.py
sklearn_numba_dpex/kmeans/kernels/compute_labels.py
sklearn_numba_dpex/kmeans/kernels/kmeans_plusplus.py
sklearn_numba_dpex/kmeans/kernels/lloyd_single_step.py

+ note: found this piece of information: https://stackoverflow.com/a/15044884 suggesting that:
+ 2D grid really are better for performance because doing // and % ops in the kernel is expensive
+ it indexes work items in a "row major order" meaning that items in the same row belong to the same sub group (/warp)
+ even if the previous information applies to cuda. I assume it's also true for numba-dpex/ sycl
It's WIP because the benchmark show that those changes induce a 30% performance overhead, there seem to be an issue with 2D grid of work items in `numba_dpex` or `SYCL`. 
Opened an issue https://github.com/IntelPython/numba-dpex/issues/941
TODO: find minimal reproducers.
This PR remains opened as WIP in case those issues are fixed eventually.
Before considering merging the PR, please …

ENH Use a 2D grid of work items where applicable

---

sklearn_numba_dpex/common/matmul.py
sklearn_numba_dpex/common/random.py
sklearn_numba_dpex/common/reductions.py
sklearn_numba_dpex/common/tests/test_matmul.py
sklearn_numba_dpex/common/tests/test_random.py
sklearn_numba_dpex/common/topk.py
sklearn_numba_dpex/kmeans/drivers.py
sklearn_numba_dpex/kmeans/kernels/lloyd_single_step.py
sklearn_numba_dpex/kmeans/kernels/utils.py
sklearn_numba_dpex/kmeans/tests/test_kmeans.py
sklearn_numba_dpex/patches/tests/test_patches.py

With this PR:
- <del>our matmul achieves 90% dpnp performance on iGPU</del> See: https://github.com/soda-inria/sklearn-numba-dpex/pull/107#issuecomment-1519389111.
- catastrophic performances on max series gpu is fixed of KMeans
also fix compatibility with latest versions of `dpctl`.
Closes https://github.com/IntelPython/numba-dpex/issues/984

Improve performance accross several kernels with better parameters

---

sklearn_numba_dpex/common/matmul.py
sklearn_numba_dpex/common/topk.py
sklearn_numba_dpex/kmeans/kernels/_base_kmeans_kernel_funcs.py
sklearn_numba_dpex/kmeans/kernels/compute_euclidean_distances.py
sklearn_numba_dpex/kmeans/kernels/compute_labels.py
sklearn_numba_dpex/kmeans/kernels/kmeans_plusplus.py
sklearn_numba_dpex/kmeans/kernels/lloyd_single_step.py

The initialization step in lloyd seemed to cause buggy behavior and a huge slowdown for some dimensions in inputs on PVC.
I didn't have time to reproduce within the timed access to the server but I experimented with removing the initialization step and found out that it seems to work just fine. 
This PR remove all initialization funcs for private arrays in all kernels.
I've opened a subsequent issues to inquiry the validity of this assumption at https://github.com/IntelPython/numba-dpex/issues/1016

Assume private arrays are created already initialized to zero

---

.github/workflows/run_tests.yaml
README.md
docker/Dockerfile
sklearn_numba_dpex/__init__.py
sklearn_numba_dpex/common/_utils.py
sklearn_numba_dpex/patches/load_numba_dpex.py

Update Dockerfile, patch around inline optimization issues, and hack around drop of atomics on CPU to keep a working CI (by pinning CI on an old working version).

MNT Update dependencies
